# Generated by Django 5.0.4 on 2024-04-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Class', models.IntegerField()),
                ('Subject', models.CharField(max_length=100)),
            ],
        ),
    ]
