# Generated by Django 5.0.3 on 2024-04-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_student_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Names']},
        ),
    ]
