# Generated by Django 5.0.3 on 2024-04-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Names']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='My_Students_List',
        ),
    ]
