# Generated by Django 5.0.3 on 2024-04-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='My_Students_List',
        ),
    ]
