# Generated by Django 5.0.4 on 2024-04-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Price', models.IntegerField()),
                ('Item_Qty', models.IntegerField()),
                ('Item_Desc', models.CharField(max_length=250)),
            ],
        ),
    ]
