# Generated by Django 5.0.3 on 2024-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelName', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(choices=[('tata', 'tata'), ('volvo', 'volvo'), ('honda', 'honda'), ('BMW', 'BMW'), ('swift', 'swift')], max_length=100)),
                ('fuelName', models.ManyToManyField(to='MTMApp.fueltypemodel')),
            ],
        ),
    ]
