# Generated by Django 5.0.3 on 2024-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ReleaseDate', models.IntegerField()),
                ('Rating', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=250)),
            ],
        ),
    ]
