# Generated by Django 5.0.3 on 2024-04-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuName', models.CharField(max_length=50, verbose_name='Name')),
                ('stuDep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='OTMApp.departmentmodel')),
            ],
        ),
    ]
