# Generated by Django 5.0.3 on 2024-04-01 17:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsSlug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='news_title', unique=True),
        ),
    ]
