# Generated by Django 5.0.3 on 2024-04-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_newsslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsSlug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
