# Generated by Django 5.0.3 on 2024-04-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_newsslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newsSlug',
            new_name='newslug',
        ),
    ]
