# Generated by Django 5.0.3 on 2024-04-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_newsslug_news_newslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newslug',
            new_name='newsSlug',
        ),
    ]
