# Generated by Django 5.0.6 on 2024-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
                ('Confirm_Password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'UserList',
            },
        ),
    ]
