# Generated by Django 5.0.6 on 2024-05-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=250)),
                ('Email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
        ),
    ]
