# Generated by Django 5.0.6 on 2024-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_querymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
